# Generated by Django 4.2.7 on 2023-12-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='u_type',
            field=models.CharField(blank=True, choices=[('FINANCE HEAD', 'FINANCE HEAD'), ('CS HEAD', 'CS HEAD'), ('RECOVERY HEAD', 'RECOVER HEAD'), ('RECOVERY AGENT', 'RECOVERY AGENT'), ('FINANCE HEAD', 'FINANCE HEAD')], max_length=40),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
