# Generated by Django 4.2.7 on 2023-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_email_user_full_name_user_u_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="u_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FINANCE HEAD", "FINANCE HEAD"),
                    ("CS HEAD", "CS HEAD"),
                    ("RECOVERY HEAD", "RECOVER HEAD"),
                    ("RECOVERY AGENT", "RECOVERY AGENT"),
                    ("FINANCE CLERK", "FINANCE CLERK"),
                ],
                max_length=40,
            ),
        ),
    ]
