# Generated by Django 4.2.7 on 2023-12-06 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="name",
        ),
        migrations.RemoveField(
            model_name="client",
            name="vat_number",
        ),
        migrations.AddField(
            model_name="client",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="balance",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="contact_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="collector",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="credit_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="guarantee_world_insurer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
