# Generated by Django 4.2.7 on 2023-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_client_name_remove_client_vat_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
