# Generated by Django 4.2.7 on 2023-12-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle6',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle7',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle8',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='inv_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='short_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.client'),
        ),
    ]
