# Generated by Django 4.2.7 on 2023-12-08 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_bill_balance_alter_bill_cycle1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='short_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client'),
        ),
    ]
