# Generated by Django 4.2.7 on 2023-12-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_bill_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
