# Generated by Django 4.2.7 on 2023-12-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_bill_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
