# Generated by Django 4.2.7 on 2023-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
