# Generated by Django 4.2.7 on 2023-12-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_bill_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField()),
                ('action_type', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('call', 'call')], max_length=20)),
                ('action_amount', models.FloatField()),
                ('short_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
            ],
        ),
    ]
