# Generated by Django 4.2.7 on 2023-12-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
