# Generated by Django 4.2.7 on 2023-12-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
