# Generated by Django 4.2.7 on 2023-12-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_client_overdue120'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='bill_no',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
