# Generated by Django 4.2.7 on 2023-12-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_action_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Call', 'Call')], max_length=20),
        ),
    ]
