# Generated by Django 4.2.7 on 2023-12-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_action_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
