# Generated by Django 4.2.7 on 2023-12-21 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_action_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='short_name',
        ),
        migrations.AlterField(
            model_name='action',
            name='bill_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.bill'),
        ),
    ]
