# Generated by Django 4.2.7 on 2023-12-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_action_short_name_alter_action_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='short_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.client'),
            preserve_default=False,
        ),
    ]
