# Generated by Django 4.2.7 on 2023-12-26 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_action_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='grant_period',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('SMS', (('Reminder', 'Reminder'), ('Gentle', 'Gentle'), ('Strong', 'Strong'), ('Final', 'Final'))), ('Email', 'Email'), ('Call', 'Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle3',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle4',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle5',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle6',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle7',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle8',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='cycle9',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(blank=True, choices=[('Advanced', 'Advanced'), ('Normal', 'Normal')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='overdue120',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='SMSFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_formats', to='sales.action')),
            ],
        ),
    ]
