# Generated by Django 4.2.7 on 2023-12-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_action_description_bill_created_client_grant_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='group',
            field=models.CharField(blank=True, choices=[('Advanced', 'Advanced'), ('Normal', 'Normal')], default='Normal', max_length=100, null=True),
        ),
    ]
