# Generated by Django 4.2.7 on 2023-12-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_client_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='subtype',
            field=models.CharField(blank=True, choices=[('Reminder', 'Reminder'), ('Gentle', 'Gentle'), ('Strong', 'Strong'), ('Final', 'Final')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Call', 'Call')], max_length=20),
        ),
    ]
