# Generated by Django 4.2.7 on 2024-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_action_subtype_alter_action_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='followup_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.DeleteModel(
            name='SMSFormat',
        ),
    ]
