# Generated by Django 4.2.7 on 2024-01-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_action_followup_date_delete_smsformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='followup_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
