# Generated by Django 4.2.7 on 2024-01-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_action_followup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='action',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
