# Generated by Django 4.2.7 on 2024-01-09 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_remove_action_bill_no_action_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
