# Generated by Django 4.2.7 on 2024-01-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0031_dailybalance"),
    ]

    operations = [
        migrations.AddField(
            model_name="action",
            name="extended_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
