# Generated by Django 4.2.7 on 2024-01-12 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_action_extended_date'),
        ('sales', '0032_userbalance'),
    ]

    operations = [
    ]
