# Generated by Django 4.2.7 on 2024-01-13 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_merge_0032_action_extended_date_0032_userbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
