# Generated by Django 4.2.7 on 2024-01-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_companybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='grant_period',
            field=models.IntegerField(default=0),
        ),
    ]
