# Generated by Django 4.2.7 on 2024-01-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0034_companybalance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="action",
            name="pause",
        ),
    ]
