# Generated by Django 4.2.7 on 2024-01-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_alter_client_grant_period'),
        ('sales', '0035_remove_action_pause'),
    ]

    operations = [
    ]
