# Generated by Django 4.2.7 on 2024-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_merge_20240118_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='grant_period',
            field=models.FloatField(default=0),
        ),
    ]
